language: node_js

node_js:
- 4.6.0

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script: npm run dist

deploy:
  provider: releases
  api_key:
    secure: P55SF8GcBrX8/WaHPIvvEwe7w+TA6wZxWsPjXdo+vDttiP3TH80Emxtb2Qh0GPYjLTxdDj9oJ0LfVyxJhpGBv4pGmkwog4fu5VoiR8VcLxsj5bJSFSvpHk8vVl33LsaTC7WXclXmWpHMvnGsKcv28R+gNqYbZcVj6+/4kRE7xt8=
  file: build/lineupjs.tar.gz
  on:
    repo: Caleydo/lineupjs
    tags: true

notifications:
  slack:
    secure: GGD+yGe3KJGYIS0mJk2xbCOHlCZhxjnK2hdXyPzZjzevTsIXLZqYU9ZUvsGb/Vy4V4KR81vLukxH7rKcYfkSYIqsnYAarMWz/QnZXi8EHeC/8k6b4zSCPhG14fL95b5pfoasoGqZfkKUPJVF38fV2yVUmzIADRfls4UDvsIURh8=
    on_success: change
    on_failure: always
